### ISSUE TITLE
Running command on mininet-sec CLI for k8s hosts raise an exception

### ISSUE THREAD

**Issue by italovalcy** [mininet-sec/mininet-sec#17]
Hi,

While running command on the kubernetes host, it raise the following exception:

```
mininet-sec> h1 ip a
Traceback (most recent call last):
  File "/usr/lib/python3.11/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CLI' object has no attribute 'do_h1'. Did you mean: 'do_px'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/mnsec/examples/kubernetes_linear3.py", line 46, in <module>
    run()
  File "/src/mnsec/examples/kubernetes_linear3.py", line 40, in run
    CLI( net )
  File "/usr/local/lib/python3.11/dist-packages/mnsec/cli.py", line 22, in __init__
    MN_CLI.__init__(self, mnsec, stdin=stdin, script=script)
  File "/usr/lib/python3/dist-packages/mininet/cli.py", line 70, in __init__
    self.run()
  File "/usr/lib/python3/dist-packages/mininet/cli.py", line 114, in run
    self.cmdloop()
  File "/usr/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/cmd.py", line 216, in onecmd
    return self.default(line)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mininet/cli.py", line 439, in default
    self.waitForNode( node )
  File "/usr/lib/python3/dist-packages/mininet/cli.py", line 447, in waitForNode
    nodePoller.register( node.stdout )
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by italovalcy** [comment]
this issue was already fixed by recent changes
